-- ==========================================================
-- SKEMA DATABASE MYSQL UNTUK HOSTINGER (phpMyAdmin)
-- Portal Administrasi SMP Maarif NU Pandaan
-- Database: u604170242_portal_maarif
-- User: u604170242_root2
-- Password: Sparifda@92
-- ==========================================================

CREATE DATABASE IF NOT EXISTS `u604170242_portal_maarif` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `u604170242_portal_maarif`;

-- 1. Tabel Siswa
CREATE TABLE IF NOT EXISTS `students` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Tagihan SPP
CREATE TABLE IF NOT EXISTS `spp_bills` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Tagihan Non-SPP / Lainnya
CREATE TABLE IF NOT EXISTS `misc_bills` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Transaksi Tabungan
CREATE TABLE IF NOT EXISTS `savings_transactions` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Transaksi Midtrans Payment Gateway
CREATE TABLE IF NOT EXISTS `midtrans_transactions` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Log Notifikasi Realtime
CREATE TABLE IF NOT EXISTS `realtime_notifications` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Log Kehadiran / Presensi Siswa
CREATE TABLE IF NOT EXISTS `attendance_logs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Wali Kelas
CREATE TABLE IF NOT EXISTS `homeroom_teachers` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Guru Mata Pelajaran
CREATE TABLE IF NOT EXISTS `subject_teachers` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. Jurnal Mengajar
CREATE TABLE IF NOT EXISTS `teaching_journals` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. Transaksi Bendahara / Kas Sekolah
CREATE TABLE IF NOT EXISTS `treasurer_transactions` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. Catatan Perkembangan Siswa
CREATE TABLE IF NOT EXISTS `student_development_logs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. Pelanggaran & Poin Siswa
CREATE TABLE IF NOT EXISTS `student_infraction_logs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. Bimbingan Konseling (BK)
CREATE TABLE IF NOT EXISTS `student_counseling_logs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 15. Pengumuman Kelas
CREATE TABLE IF NOT EXISTS `class_announcements` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 16. Notulen Rapat & Pertemuan Kelas
CREATE TABLE IF NOT EXISTS `class_meeting_logs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 17. Asesmen Kurikulum Merdeka
CREATE TABLE IF NOT EXISTS `merdeka_assessments` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 18. Jadwal Pelajaran
CREATE TABLE IF NOT EXISTS `class_schedules` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 19. Program Kerja Kepala Sekolah
CREATE TABLE IF NOT EXISTS `principal_work_programs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 20. Evaluasi Guru
CREATE TABLE IF NOT EXISTS `teacher_evaluations` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 21. Aturan Pelanggaran
CREATE TABLE IF NOT EXISTS `infraction_rules` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 22. Inventaris Sarpras
CREATE TABLE IF NOT EXISTS `sarpras_items` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 23. Pengajuan Sarpras
CREATE TABLE IF NOT EXISTS `sarpras_proposals` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 24. Peminjaman Sarpras
CREATE TABLE IF NOT EXISTS `sarpras_loans` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 25. Gaji & Honor Guru
CREATE TABLE IF NOT EXISTS `teacher_salaries` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 26. Pendaftar SPMB
CREATE TABLE IF NOT EXISTS `spmb_candidates` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 27. Konfigurasi Sistem
CREATE TABLE IF NOT EXISTS `configs` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 28. Riwayat Backup Database
CREATE TABLE IF NOT EXISTS `database_backups` (
  `id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
